language: node_js
node_js: node
os:
- linux
- osx
dist: trusty
sudo: true
osx_image: xcode8.3
git:
  depth: 3

install:
  - npm i
  
script:
  - npm --version

notifications:
  email:
    on_success: never
